up:
	@migrate -path ./migrations -database "mysql://root:password@tcp(localhost:3306)/authentication" -verbose up

down:
	@migrate -path ./migrations -database "mysql://root:password@tcp(localhost:3306)/authentication" -verbose down