up:
	@migrate -path ./migrations -database "mysql://root:password@tcp(localhost:8001)/authentication" -verbose up

down:
	@migrate -path ./migrations -database "mysql://root:password@tcp(localhost:8001)/authentication" -verbose down