{
 "title": "E-commerce",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avrg Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum/http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{severity=~\"error|info|warning\"} |= ``"
    }
   ]
  }
 ]
}