apiVersion: 1

deleteDatasources:
  - name: loki
    orgId: 1

datasources:
- name: loki
  type: loki
  typeName: Loki
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  readOnly: true

- name: prometheus
  type: prometheus
  typeName: prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  readOnly: true

