services:
  # Databases
  # Auth DBs
  auth-mysql:
    image: mysql:8.3.0
    container_name: auth-mysql
    networks:
      - ecommerce
    ports:
      - "${AUTHENTICATION_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${AUTHENTICATION_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=authentication

  auth-redis:
    image: redis:7.2.4-alpine
    container_name: auth-redis
    networks:
      - ecommerce
    ports:
      - "${AUTHENTICATION_REDIS_PORT}:6379"

  # account-mongodb:
  #   image: mongo
  #   container_name: account-mongodb
  #   networks:
  #     - ecommerce
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${ACCOUNT_MONGO_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${ACCOUNT_MONGO_ROOT_PASSWORD}
  #   ports:
  #     - "${ACCOUNT_MONGO_ROOT_PORT}:27017"

networks:
  ecommerce:
    driver: bridge
