services:
  # Kafka
  kafka:
    build:
      context: ../docker/kafka
      dockerfile: ./Dockerfile
    container_name: kafka
    ports:
      - ${KAFKA_EXTERNAL_PORT}:9092
    networks:
      - ecommerce
    healthcheck:
      test:
        ["CMD-SHELL", "./wait-for.sh kafka:${KAFKA_PORT} -- ./kafka_setup.sh"]
      interval: 30s
      timeout: 30s
      retries: 100
      start_period: 30s

  mail:
    build:
      context: ../../
      dockerfile: ./builds/docker/mail/Dockerfile
    container_name: mail
    image: ecommerce/mail
    networks:
      - ecommerce
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_HOST=${KAFKA_HOST}
    command: ["./app"]
    depends_on:
      kafka:
        condition: service_healthy

networks:
  ecommerce:
    driver: bridge
